### PR TITLE
Fc32

### PR DESCRIPTION
**Pull request by fepitre**
QubesOS/qubes-issues#5763

### CODE REVIEW

**Review by Rudd-O — APPROVED** [review]
But note @marmarek 's comments.

**Comment by fepitre** [comment]
Its already a known fact. I don't understand your point.

**Comment by marmarek** [comment]
I don't like setting epoch here. It would force us to maintain this package for quite some time, even after Fedora releases fixed version. Because it will always be considered newer than the Fedora's one. The only option would be manual "downgrade" (or distro-sync) when migrating to the next Fedora version. This is especially bad, since we consider this workaround for VM package too.

Can we have some less intrusive (reversible) option? Maybe set release higher than Fedora (and watch closely for Fedora updates, like `3000.3` currently in the pipeline)? Or maybe require specific version somewhere (in a meta-package? or other qubes salt package?)?

**Comment by fepitre** [comment]
I think we can go on having higher release until the problem is fixed and watch Fedora updates. The delay between testing and stable would let us enough time for updating release if needed.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
